"""to int

Revision ID: 0061f0fd9b9a
Revises: dfff2f69a402
Create Date: 2025-07-08 12:54:26.988231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0061f0fd9b9a'
down_revision: Union[str, None] = 'dfff2f69a402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE asset
        ALTER COLUMN blockchain_user_will_id TYPE INTEGER
        USING blockchain_user_will_id::integer
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'blockchain_user_will_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
