"""added isnowdue

Revision ID: 552fc2c5b6e3
Revises: 83eee51efd0b
Create Date: 2025-07-19 10:45:37.601071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552fc2c5b6e3'
down_revision: Union[str, None] = '83eee51efd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('is_now_due_date', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'is_now_due_date')
    # ### end Alembic commands ###
