"""distributed to asset

Revision ID: 83eee51efd0b
Revises: 0061f0fd9b9a
Create Date: 2025-07-09 08:28:58.035083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83eee51efd0b'
down_revision: Union[str, None] = '0061f0fd9b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('distributed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'distributed')
    # ### end Alembic commands ###
