"""new update

Revision ID: 8786777f125b
Revises: 
Create Date: 2025-07-06 14:04:29.547111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8786777f125b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('validated_created', sa.Boolean(), nullable=True))
    op.add_column('asset', sa.Column('validated_funds', sa.Boolean(), nullable=True))
    op.alter_column('asset', 'txhash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'asset', ['txhash'])
    op.drop_constraint(op.f('asset_trigger_condition_id_fkey'), 'asset', type_='foreignkey')
    op.drop_column('asset', 'trigger_condition_id')
    op.add_column('triggercondition', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.execute("""
    ALTER TABLE triggercondition
    ALTER COLUMN value TYPE INTEGER
    USING value::integer
""")
    op.create_foreign_key(None, 'triggercondition', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'triggercondition', type_='foreignkey')
    op.alter_column('triggercondition', 'value',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('triggercondition', 'asset_id')
    op.add_column('asset', sa.Column('trigger_condition_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('asset_trigger_condition_id_fkey'), 'asset', 'triggercondition', ['trigger_condition_id'], ['id'])
    op.drop_constraint(None, 'asset', type_='unique')
    op.alter_column('asset', 'txhash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('asset', 'validated_funds')
    op.drop_column('asset', 'validated_created')
    # ### end Alembic commands ###
