"""added some fields

Revision ID: dfff2f69a402
Revises: 8786777f125b
Create Date: 2025-07-07 18:23:42.802777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dfff2f69a402'
down_revision: Union[str, None] = '8786777f125b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('txhash_funded', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('asset', sa.Column('blockchain_user_will_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'asset', ['txhash_funded'])
    op.create_unique_constraint(None, 'asset', ['blockchain_user_will_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='unique')
    op.drop_constraint(None, 'asset', type_='unique')
    op.drop_column('asset', 'blockchain_user_will_id')
    op.drop_column('asset', 'txhash_funded')
    # ### end Alembic commands ###
